// Chunky pixel art — 32x32-ish, limited palette, drawn with rect grid
const PX = {
  bg: '#5b8c3f',
  bgDark: '#467030',
  bgLight: '#7da856',
  honey: '#e8a13a',
  honeyDark: '#a85e15',
  honeyLight: '#f7d27a',
  bee: '#1b1410',
  beeYellow: '#f6c83c',
  hornet: '#a83a18',
  hornetDark: '#5a1c0a',
  human: '#ece1c1',
  humanShade: '#a8987c',
  white: '#f5efe0',
};

// Render a sprite from a string grid. '.' = transparent.
function PxSprite({ data, palette, scale = 6, w = 32, h = 32 }) {
  const rows = data.trim().split('\n').map((r) => r.replace(/\s/g, ''));
  return (
    <g>
      {rows.map((row, y) =>
        [...row].map((ch, x) => {
          if (ch === '.' || !palette[ch]) return null;
          return (
            <rect
              key={`${x}-${y}`}
              x={x * scale}
              y={y * scale}
              width={scale}
              height={scale}
              fill={palette[ch]}
              shapeRendering="crispEdges"
            />
          );
        })
      )}
    </g>
  );
}

function PxTile({ children, gridScale = 6.875 /* 32*6.875=220 */ }) {
  // background grass tile pattern
  const bgRows = [];
  for (let y = 0; y < 32; y++) {
    let row = '';
    for (let x = 0; x < 32; x++) {
      // deterministic noise
      const n = ((x * 13 + y * 7 + x * y) % 17);
      if (n < 2) row += 'd';
      else if (n < 5) row += 'l';
      else row += 'g';
    }
    bgRows.push(row);
  }
  const bgData = bgRows.join('\n');
  return (
    <svg viewBox="0 0 220 220" width="100%" height="100%" style={{ display: 'block', imageRendering: 'pixelated' }}>
      <g>
        <PxSprite data={bgData} palette={{ g: PX.bg, d: PX.bgDark, l: PX.bgLight }} scale={gridScale} />
      </g>
      {/* sprite layer centered */}
      <g transform="translate(14, 14)">{children}</g>
    </svg>
  );
}

// 32x32 sprites
const HIVE_SPRITE = `
................................
................................
................................
.........kkkkkkkkkkkkkk.........
........kHHHHHHHHHHHHHHk........
.......kHwwHHHHHHHHHHwwHk.......
.......kHHHHHHHHHHHHHHHHk.......
......kHHHwwHHHHHHHHwwHHHk......
......hHHHHHHHHHHHHHHHHHHh......
......hHHHwwHHHHHHHHwwHHHh......
......hHHHHHHHHHHHHHHHHHHh......
......hHHHwwHHHHHHHHwwHHHh......
......hHHHHHHHHHHHHHHHHHHh......
......hHHHHHHHbbbbHHHHHHHh......
......hHHHHHHHbbbbHHHHHHHh......
......dddddddddddddddddddd......
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
`;

function PxHive() {
  // Recommendation: hanging comb (wood-ish slats with hexagon dots) — classic game read
  return (
    <PxTile>
      <PxSprite
        data={HIVE_SPRITE}
        palette={{
          k: PX.bee,
          H: PX.honey,
          h: PX.honeyDark,
          w: PX.honeyLight,
          b: PX.bee,
          d: PX.bee,
        }}
        scale={6}
      />
    </PxTile>
  );
}

const SWARM_SPRITE = `
................................
................................
................................
.........y......................
........yky.....................
.........y......................
............y...................
...........yky..................
............y...................
.....y..........................
....yky.........y...............
.....y.........yky..............
................y...............
............................y...
.......y...................yky..
......yky....y..............y...
.......y....yky.................
............y...................
.......................y........
......................yky.......
.......................y........
................................
................y...............
...............yky..............
................y...............
................................
................................
................................
................................
................................
................................
................................
`;

function PxSwarm() {
  return (
    <PxTile>
      <PxSprite data={SWARM_SPRITE} palette={{ y: PX.beeYellow, k: PX.bee }} scale={6} />
    </PxTile>
  );
}

const WORKER_SPRITE = `
................................
................................
................................
................................
................................
................................
.............kkkkkk.............
............kkkkkkkk............
...........kkkkkkkkkk...........
....ww.....kk.kkkk.kk.....ww....
...wwww...kkkkkkkkkkkk...wwww...
..wwwwww..kyyyyyyyyyyk..wwwwww..
..wwwwww..kkkkkkkkkkkk..wwwwww..
...wwww...kyyyyyyyyyyk...wwww...
....ww....kkkkkkkkkkkk....ww....
..........kyyyyyyyyyyk..........
..........kkkkkkkkkkkk..........
...........kkkkkkkkkk...........
............kkkkkkkk............
.............kk..kk.............
..............kkkk..............
...............kk...............
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
`;

function PxWorker() {
  return (
    <PxTile>
      <PxSprite
        data={WORKER_SPRITE}
        palette={{ k: PX.bee, y: PX.beeYellow, w: PX.white }}
        scale={6}
      />
    </PxTile>
  );
}

const HORNET_SPRITE = `
................................
................................
................................
................................
.............kkkkkk.............
............khhhhhhk............
...........khhdddhhhk...........
...........khdkkkkdhk...........
.....w......khhhhhhk......w.....
....www....hhhhhhhhhh....www....
...wwwww..hhhhhhhhhhhh..wwwww...
....www...hkkkkkkkkkkh...www....
.....w....hhhhhhhhhhhh....w.....
..........hkkkkkkkkkkh..........
..........hhhhhhhhhhhh..........
..........hkkkkkkkkkkh..........
..........hhhhhhhhhhhh..........
...........hhhhhhhhhh...........
............hhhhhhhh............
.............hh..hh.............
..............kkkk..............
...............kk...............
...............kk...............
................................
................................
................................
................................
................................
................................
................................
................................
................................
`;

function PxHornet() {
  return (
    <PxTile>
      <PxSprite
        data={HORNET_SPRITE}
        palette={{ k: PX.bee, h: PX.hornet, d: PX.hornetDark, w: PX.white }}
        scale={6}
      />
    </PxTile>
  );
}

const KEEPER_SPRITE = `
................................
.............kkkkkk.............
...........kkmmmmmmkk...........
..........kmmmmmmmmmmk..........
.........kmmkkkkkkkkmmk.........
.........kmkkkkkkkkkkmk.........
.........kmkkkkkkkkkkmk.........
.........kmkkkkkkkkkkmk.........
..........kmmkkkkkkmmk..........
.....ww....kkmmmmmmkk....ww.....
....wwww....kkkkkkkk....wwww....
...wwwwww..uuuuuuuuuu..wwwwww...
....wwww..uuhhhhhhhhuu..wwww....
....ssss..uuhhhhhhhhuu..wwww....
...sshhss.uuuhhhhhhuuu..........
...sshhss.uuuuhhhhuuuu..........
....ssss..uuuuhhhhuuuu..........
...sshhss.uuuuhhhhuuuu..........
...sshhss.uuuhhhhhhuuu..........
....ssss..uuuhhhhhhuuu..........
...sshhss.uuuuhhhhuuuu..........
....kkkk..uuuuhhhhuuuu..........
...kkkkkk.uuuuhhhhuuuu..........
....kkkk..uuuhhhhhhuuu..........
..........uuhhhhhhhhuu..........
..........uuhhhhhhhhuu..........
...........uhhhhhhhhu...........
............uuuuuuuu............
.............uuuuuu.............
................................
................................
................................
`;

function PxBeekeeper() {
  return (
    <PxTile>
      <PxSprite
        data={KEEPER_SPRITE}
        palette={{
          k: PX.bee,
          m: PX.humanShade,
          u: PX.human,
          h: PX.bee,        // dark veil/center
          w: PX.white,      // smoke
          s: PX.honeyDark,  // smoker body
        }}
        scale={6}
      />
    </PxTile>
  );
}

window.PX_STYLE = { PxHive, PxSwarm, PxWorker, PxHornet, PxBeekeeper, PX };
